### ISSUE TITLE
Build failure vtkParallelTransportTest1.cxx

### ISSUE THREAD

**Issue by jcfr** [Slicer/vtkAddon#64]
Fix regression introduced in https://github.com/Slicer/vtkAddon/commit/cf1126568415179fb5b1c16121087bd2494e2e0e

```
vtkAddon/Testing/vtkParallelTransportTest1.cxx:108:7: error: ‘tangentsArray’ was not declared in this scope; did you mean ‘tangents’?
```

Source: https://slicer.cdash.org/viewBuildError.php?buildid=4005586

---

Related pull request:
* https://github.com/Slicer/vtkAddon/pull/59

**Comment by jcfr** [comment]
@hjmjohnson Do you think you could have a look ? 🙏 

This broke the current Preview build

cc: @lassoan @jamesobutler @sjh26 @ebrahimebrahim
